2025-05-14 13:49:34 [food.spiders.ingredients] WARNING: Crawling completed in 0:05:38.730892
2025-05-14 14:09:17 [food.spiders.ingredients] WARNING: Crawling completed in 0:06:01.970228
2025-05-20 12:16:28 [twisted] CRITICAL: Unhandled error in Deferred:
2025-05-20 12:16:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\twisted\internet\defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\crawler.py", line 156, in crawl
    self.engine = self._create_engine()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\crawler.py", line 169, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\core\engine.py", line 111, in __init__
    self.scraper: Scraper = Scraper(crawler)
                            ^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\core\scraper.py", line 107, in __init__
    self.itemproc: ItemPipelineManager = itemproc_cls.from_crawler(crawler)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\middleware.py", line 86, in _from_settings
    mwcls = load_object(clspath)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\misc.py", line 71, in load_object
    mod = import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\hp\bb-team-info-by-ingredient\food\food\pipelines.py", line 3, in <module>
    from nutrient_headers import NUTRIENT_HEADERS
ModuleNotFoundError: No module named 'nutrient_headers'
2025-05-20 12:33:31 [twisted] CRITICAL: Unhandled error in Deferred:
2025-05-20 12:33:31 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\twisted\internet\defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\crawler.py", line 156, in crawl
    self.engine = self._create_engine()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\crawler.py", line 169, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\core\engine.py", line 111, in __init__
    self.scraper: Scraper = Scraper(crawler)
                            ^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\core\scraper.py", line 107, in __init__
    self.itemproc: ItemPipelineManager = itemproc_cls.from_crawler(crawler)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\middleware.py", line 86, in _from_settings
    mwcls = load_object(clspath)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\misc.py", line 71, in load_object
    mod = import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fodd'
2025-05-20 12:37:15 [ingredients] WARNING: Failed to convert quantity: 1.677.60 in https://www.bb-team.org/hrani/id/271918_atserola-zapadno-indiyska-cheresha-surova (Витамин C)
2025-05-20 12:38:22 [ingredients] WARNING: Failed to convert quantity: 2.403.30 in https://www.bb-team.org/hrani/id/338677_yaytse-zheltak-izsushen (Витамин B4 (Холин))
2025-05-20 12:39:23 [ingredients] WARNING: Failed to convert quantity: 1.359.50 in https://www.bb-team.org/hrani/id/853352_koriandar-sushen (Витамин K1)
2025-05-20 12:39:27 [ingredients] WARNING: Failed to convert quantity: 1.266.70 in https://www.bb-team.org/hrani/id/534966_yaytse-tsyalo-susheno (Витамин B4 (Холин))
2025-05-20 12:39:33 [ingredients] WARNING: Failed to convert quantity: 1.714.50 in https://www.bb-team.org/hrani/id/567464_mashterka-babina-dushitsa-sushena (Витамин K1)
2025-05-20 12:39:33 [ingredients] WARNING: Failed to convert quantity: 1.714.50 in https://www.bb-team.org/hrani/id/454644_gradinski-chay-mlyan (Витамин K1)
2025-05-20 12:39:34 [ingredients] WARNING: Failed to convert quantity: 1.359.50 in https://www.bb-team.org/hrani/id/961018_magdanoz-sushen (Витамин K1)
2025-05-20 12:39:36 [ingredients] WARNING: Failed to convert quantity: 1.714.50 in https://www.bb-team.org/hrani/id/437201_bosilek-izsushen (Витамин K1)
2025-05-20 12:40:40 [food.spiders.ingredients] WARNING: Crawling completed in 0:03:34.164072
2025-05-20 12:53:48 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:49 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:53:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x000002081E1924D0>>
Traceback (most recent call last):
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\utils\defer.py", line 417, in maybeDeferred_coro
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\extensions\feedexport.py", line 639, in item_scraped
    slot.exporter.export_item(item)
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in export_item
    values = list(self._build_row(x for _, x in fields))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 274, in _build_row
    for s in values:
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 267, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\scrapy\exporters.py", line 78, in _get_serialized_fields
    item = ItemAdapter(item)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\bb-team-info-by-ingredient\.venv\Lib\site-packages\itemadapter\adapter.py", line 331, in __init__
    raise TypeError(f"No adapter found for objects of type: {type(item)} ({item})")
TypeError: No adapter found for objects of type: <class 'NoneType'> (None)
2025-05-20 12:57:04 [ingredients] WARNING: Failed to convert quantity: 1.677.60 in https://www.bb-team.org/hrani/id/271918_atserola-zapadno-indiyska-cheresha-surova (Витамин C)
2025-05-20 12:58:30 [ingredients] WARNING: Failed to convert quantity: 2.403.30 in https://www.bb-team.org/hrani/id/338677_yaytse-zheltak-izsushen (Витамин B4 (Холин))
2025-05-20 12:59:37 [ingredients] WARNING: Failed to convert quantity: 1.359.50 in https://www.bb-team.org/hrani/id/853352_koriandar-sushen (Витамин K1)
2025-05-20 12:59:41 [ingredients] WARNING: Failed to convert quantity: 1.266.70 in https://www.bb-team.org/hrani/id/534966_yaytse-tsyalo-susheno (Витамин B4 (Холин))
2025-05-20 12:59:47 [ingredients] WARNING: Failed to convert quantity: 1.714.50 in https://www.bb-team.org/hrani/id/567464_mashterka-babina-dushitsa-sushena (Витамин K1)
2025-05-20 12:59:47 [ingredients] WARNING: Failed to convert quantity: 1.714.50 in https://www.bb-team.org/hrani/id/454644_gradinski-chay-mlyan (Витамин K1)
2025-05-20 12:59:48 [ingredients] WARNING: Failed to convert quantity: 1.359.50 in https://www.bb-team.org/hrani/id/961018_magdanoz-sushen (Витамин K1)
2025-05-20 12:59:50 [ingredients] WARNING: Failed to convert quantity: 1.714.50 in https://www.bb-team.org/hrani/id/437201_bosilek-izsushen (Витамин K1)
2025-05-20 13:00:52 [food.spiders.ingredients] WARNING: Crawling completed in 0:03:55.791634
